### ISSUE TITLE
Feature request: focus on first input element using gi

### ISSUE THREAD

**Issue by pequodification** [ueokande/vim-vixen#153] opened 2017-11-13 11:45 UTC
### I'm opening this issue because:

- [ ] I'll report a bug
- [x] I'll propose a new feature

### Description
One simple feature I've been missing from Vimperator is being able to focus on the first input box by pressing g followed by i.

**Comment by ainola** [comment] 2017-11-14 01:26
Duplicate of https://github.com/ueokande/vim-vixen/issues/98

**Closed** 2018-01-14 00:32 UTC
Labels: enhancement
