### ISSUE TITLE
"Could not establish connection. Receiving end does not exist." when doing a search

### ISSUE THREAD

**Issue by gobenji** [ueokande/vim-vixen#1243] opened 2021-08-20 02:01 UTC
### I'm opening this issue because:

- [x] I'll report a bug

### Description

Sometimes, when using the search functionality (type "/", type search terms, press Enter), a message in red is displayed at the bottom of the browser window: "Could not establish connection. Receiving end does not exist.". The search functionality does not work.

#### Steps to Reproduce

I don't know how to reproduce the issue systematically. It seems to occur more often on some pages. On pages where it sometimes does not work, it sometimes works also. Reloading the page does not seem to help. Opening another tab and searching for some text which is already visible in the window and then going back to the tab where the error occurred seems to help sometimes (repeating the search works at that point).

#### System configuration

- Operating system: Debian GNU/Linux 11 (bullseye)
- Firefox version: 88.0.1 (64-bit)
- Vim-Vixen version: 1.2.2

#### Console logs

Any relevant log in developer tools:
No message when the problem occurs.

When using the workaround described above (doing a search in another tab), after going back to the tab where the search did not work, the following message is repeated a few times with different "window frame" numbers:
```
Failed to add shortcut on window frame 17: SecurityError: Permission denied to access property "addEventListener" on cross-origin object
shortcut.js:214:14
moz-extension://87eef6e0-d9bf-48f8-b84d-19befd6cff31/shortcut.js
```
I guess this message is related to vim-vixen.

**Comment by gobenji** [comment] 2021-08-22 05:04
> I don't know how to reproduce the issue systematically.

I've been able to reproduce it repeatedly when visiting https://www.bbc.com/news/technology-58206543

Here is a screen recording that shows the issue:
https://user-images.githubusercontent.com/254681/130342805-a4dbfc0b-6ee0-4925-82de-c0b346b2df54.mp4

> When using the workaround described above (doing a search in another tab),
> after going back to the tab where the search did not work, the following
> message is repeated a few times

It turns out that for a workaround, it is sufficient to wait a little bit; switching between tabs and doing another search is not necessary. The error message mentioned earlier appears after ~20s and then the search function works.

**Comment by dmusican** [comment] 2021-08-24 14:47
I'm seeing the same issue.

**Comment by antgel** [comment] 2021-08-28 14:31
> I'm seeing the same issue.

You can just hit the +1 to vote for the issue, and subscribe. Every comment here spams everyone (yes I'm aware of the irony).

**Comment by ueokande** [comment] 2021-09-22 09:37
Thank you for your reporting.  The issues is caused by #1213 (Cross frame search).

I'm investigating this issues and it will be fixed as soon as possible.

**Closed** 2021-09-26 02:54 UTC
Labels: bug

**Comment by ueokande** [comment] 2021-09-26 04:01
The fixed versions is released as version 1.2.3. Thank you!

**Comment by pacalet** [comment] 2021-11-22 14:06
This issue is not 100% solved with version 1.2.3, I am afraid. I still see this red message when visiting, for instance, https://www.wordreference.com/fren/bug and searching some random string.

### System configuration

- Operating system: macOS 10.14.6 (Mojave)
- Firefox version: 94.0.1 (64-bit)
- Vim-Vixen version: 1.2.3

Shall I open a new issue?

**Comment by gobenji** [comment] 2021-12-13 08:06
> This issue is not 100% solved with version 1.2.3, I am afraid. I still see this red message when visiting, for instance, https://www.wordreference.com/fren/bug and searching some random string.

I cannot reproduce the issue on https://www.wordreference.com/fren/bug and no longer see the issue on https://www.bbc.com/news/technology-58206543 however I just noticed that it occurs on https://docs.aiohttp.org/en/stable/client_reference.html

There are no messages in the console at the time of the problem or shortly thereafter (I waited a few minutes but let's say 60s). I don't know of a workaround.

I noticed that if I disable vim-vixen in the offending tab (by clicking the vim-vixen toolbar button), the following message appears in the console at that moment:
```
Failed to add shortcut on window frame 0: SecurityError: Permission denied to access property "addEventListener" on cross-origin object shortcut.js:214:14
```
Given that this is the same message that I saw originally, I guess the problem is related.

At this time my configuration is
* Operating system: Debian GNU/Linux bookworm/sid
* Firefox version: 94.0.2 (64-bit)
* Vim-vixen version: 1.2.3

**Comment by bbenne10** [comment] 2022-01-25 13:34
Just a note that I'm still seeing this bug as well. I had assumed that I had failed to install some companion application (as I needed for PassFF, for instance), but muscle-memoried a search on the vim-vixen documentation page and had it work. 

The page I'm having trouble on is https://docs.python.org/3/library/subprocess.html. I did a search for "Popen" just after opening the page and received the same error mentioned above. I am on 1.2.3 on FF version 96.0.2 on macOS Catalina.

I wasn't able to get the same `SecurityError` as mentioned above to appear, so I'm afraid it might be a red herring? That's just a gut feeling though.

**Comment by gobenji** [comment] 2022-01-26 01:58
> I cannot reproduce the issue on https://www.wordreference.com/fren/bug and no longer see the issue on https://www.bbc.com/news/technology-58206543 however I just noticed that it occurs on https://docs.aiohttp.org/en/stable/client_reference.html

Well, I'm both embarrassed and happy to say that I cannot reproduce the issue at all anymore. I'm not sure what changed though.

> The page I'm having trouble on is https://docs.python.org/3/library/subprocess.html. I did a search for "Popen" just after opening the page and received the same error mentioned above. I am on 1.2.3 on FF version 96.0.2 on macOS Catalina.

I also cannot reproduce it on that site.

@ueokande is there more specific debug information that we can gather if/when we see similar symptoms occur again, ie. "Could not establish connection. Receiving end does not exist." when doing a search?

**Comment by dieggsy** [comment] 2022-02-07 01:58
I'm still seeing this issue sometimes (Fedora 35, Firefox 96 from repos, Vim Vixen 1.2.3), but I haven't found reliable reproduction steps.

**Comment by SkyLeach** [comment] 2022-02-11 18:55
This has become the bane of my existence because it comes up all the time and when it comes up both Vim-Vixen and find+ (regex) break and quite possibly for the same reason: the missing promise.

This issue seems to have a really good explanation of the problem and solution on `stackoverflow`:

https://stackoverflow.com/questions/41624852/messaging-problems-between-content-script-and-background-script-webextensions

And, since it's such a PITA and waste of productivity it got me investigating it (even though I really don't have time) and looking at the use of simple wildcards instead of real vim regex.

I wonder if it might be possible to combine the fix for this and Find+ to have real search/substitute with vim-style regex in the browser?  It's there in javascript, there is an existing extension that could be partnered with to provide it, can we please explore combining them?

**Comment by jakkdl** [comment] 2022-07-27 11:01
+1 to SkyLeach, it happens to me regularly. Could this issue please be reopened?
