### ISSUE TITLE
Prev/next tab key bindings don't work until page is loaded

### ISSUE THREAD

**Issue by casperravenhorst** [ueokande/vim-vixen#379] opened 2018-04-28 08:16 UTC
### I'm opening this issue because:

- [X] I'll report a bug
- [ ] I'll propose a new feature

### Description
In my current config, I like to use h/l for tab prev/next. One problem; it doesn't work on a lot of pages, like the ones that are not loaded yet.

### Failure Information (for bugs)
-

#### Steps to Reproduce

1. Open a new tab
2. Type a URL
3. Press your previous tab keycombo

Results
4a. It won't, gotta wait

Expected results
4b. It will

#### System configuration

- Operating system: Mac
- Firefox version: 59.0.2
- Vim-Vixen version: 0.12

#### Console logs

Any relevant log in developer tools:
-

**Comment by AlexeySachkov** [comment] 2018-04-28 08:26
Looks like duplicate of #156

**Comment by ueokande** [comment] 2018-05-22 12:46
duplicated

**Closed by ueokande** 2018-05-22 12:46 UTC
