### ISSUE TITLE
Add :help to open commands list

### ISSUE THREAD

**Issue by cirelli94** [ueokande/vim-vixen#605] opened 2019-06-11 16:06 UTC
### I'm opening this issue because:

- [ ] I'll report a bug
- [ X] I'll propose a new feature

### Description
It would be helpful to have a fast way to check commands, I think and :h or :help command should be fine.

#### Steps to Reproduce
Open Console command
Type `:h` or `:help`
Please provide detailed steps for reproducing the issue.

I'd like to do this by myself, as a contributor.

**Comment by AlexeySachkov** [comment] 2019-06-11 16:59
Looks like duplicate of #239

**Comment by ueokande** [comment] 2019-06-12 07:04
see #239

**Closed by ueokande** 2019-06-12 07:04 UTC
