### ISSUE TITLE
Loaded settings is invalid

### ISSUE THREAD

**Issue by minusf** [ueokande/vim-vixen#725] opened 2020-03-16 10:25 UTC
### I'm opening this issue because:

- [x] I'll report a bug
- [ ] I'll propose a new feature

### Description

<img width="344" alt="Screenshot 2020-03-16 at 10 40 09" src="https://user-images.githubusercontent.com/3632883/76746953-a3333500-6778-11ea-8f17-d32576796049.png">

The settings seem to be working. But I get this warning every time i start firefox.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. start Firefox

#### System configuration

- Operating system: macos catalina 10.15.3
- Firefox version: 74.0
- Vim-Vixen version: 0.27

#### Console logs

Any relevant log in developer tools:

**Comment by adriangonz** [comment] 2020-03-17 09:36
Can this be a duplicate of #722?

**Comment by minusf** [comment] 2020-03-17 13:30
yep, it is.  but switching between the formats did not fix it for me...

**Comment by minusf** [comment] 2020-04-03 11:29
any chance this can be fixed?

**Comment by mvhulten** [comment] 2020-06-01 16:20
In a lame attempt to load the defaults (and hopefully fix this issue), I removed the JSON configuration, but now Vim-Vixen is useless because none of the keybindings are configured.

As a quick work-around, could someone post (a link to) the JSON Vim-Vixen default configuration?

Apropos, I find the default settings really fine; a button *load default configuration* would be great as well.

**Comment by Quoor8ee** [comment] 2020-07-04 17:00
I find this very annoying too. Any time I install Firefox and Vim Vixen on it, it is complaining about invalid syntax. It might point to a sorry state of software quality if the factory defaults are invalid already, I don't know if that is intentional by the authors. At least, it works for me to switch from JSON to the UI configuration like described in bug #722

Nonetheless, have my working config here (modifications are J K for changing tabs, and ditched commerical search engines): https://curlpaste.com/web/sa8aan

**Comment by minusf** [comment] 2020-07-05 14:55
sadly flipping between json/form does not work for me as the settings are auto synced from firefox sync.

**Comment by mvhulten** [comment] 2020-07-08 17:27
Is it possible to add an option to load the default configuration (which could also maybe proposed to the user when it comes across an invalid configuration)?  And then we have to hope that Firefox Sync is picking up this new configuration.

**Comment by Quoor8ee** [comment] 2020-07-09 09:54
> Is it possible to add an option to load the default configuration (which could also maybe proposed to the user when it comes across an invalid configuration)?

That sounds like a bad idea (infinite loop) as long as the default configuration is invalid.

**Closed** 2020-12-13 03:35 UTC

**Comment by letscho123** [comment] 2021-04-02 20:46
Hi, I have the same problem and I cannot click the json option, so I guess I don't have the json file anymore. In which location and under which name do I have to create the json file?
